apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: crkang
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30007 # 선택적으로 지정된 노드 포트 (30000-32767 범위 내에서 선택)
